version: '3.8'

services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  mc-server:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: PAPER
    stdin_open: true
    tty: true
    volumes:
      - ./.data:/data
    links:
      - cache

volumes:
  cache:
    driver: local